version: '3.9'

services:
  db:
    ports:
      - 5432:5432
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mines
      POSTGRES_PASSWORD: mines
      POSTGRES_DB: mines

  sonar_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mines
      POSTGRES_PASSWORD: mines
      POSTGRES_DB: mines

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar_db:5432/mines
      - SONARQUBE_JDBC_USERNAME=mines
      - SONARQUBE_JDBC_PASSWORD=mines

  jenkins:
    image: jenkins/jenkins
    volumes:
    - /home/sam/IdeaProjects/mines2021:/var/jenkins_home/workspace/mines
    - /home/sam/.sdkman/candidates/java/current:/usr/share/java16
    environment:
      - JAVA_HOME=/usr/share/java16
    ports:
      - "8081:8080"
